DROP SCHEMA PUBLIC CASCADE;

CREATE TABLE client (
  contact_id      INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name            VARCHAR(64) NOT NULL,
  phone_number    VARCHAR(32) NOT NULL,
  PRIMARY KEY (contact_id)
);

CREATE TABLE products (
  application_id  INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  dt_created      TIMESTAMP DEFAULT now() NOT NULL,
  product_name    VARCHAR(128) NOT NULL,
  client_id       INTEGER NOT NULL,
  PRIMARY KEY (application_id),
  FOREIGN KEY (client_id) REFERENCES client(contact_id) ON DELETE CASCADE
);